-- Add migration script here
-- Create addresses table
DROP TABLE IF EXISTS address;

-- CREATE TABLE address(
--    contact_id INT GENERATED ALWAYS AS IDENTITY,
--    customer_id INT,
--    contact_name VARCHAR(255) NOT NULL,
--    phone VARCHAR(15),
--    email VARCHAR(100),
--    PRIMARY KEY(contact_id),
--    CONSTRAINT fk_customer
--       FOREIGN KEY(customer_id) 
--       REFERENCES customers(customer_id)
-- );

CREATE TABLE IF NOT EXISTS addresses(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    user_id INT,
    derivation_path TEXT NOT NULL,
    child_pubk_1 TEXT NOT NULL,
    child_pubk_2 TEXT NOT NULL,
    service_pubk TEXT NOT NULL,
    CONSTRAINT fk_users
      FOREIGN KEY(user_id) 
	  REFERENCES users(id)
);