-- Add migration script here
-- Create users table
DROP TABLE IF EXISTS users;

-- CREATE TABLE users(
--    id INT GENERATED ALWAYS AS IDENTITY,
--    customer_name VARCHAR(255) NOT NULL,
--    PRIMARY KEY(customer_id)
-- );

CREATE TABLE IF NOT EXISTS users(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    xpub1 TEXT NULL,
    xpub2 TEXT NULL
);
